Allow user to use CustomEventProcessor as Scoped Dependency (AddScoped)
getsentry/sentry-dotnet pull request #1979
Opened 2022-10-08 15:40 UTC by chrisza4

Refer from issue #318 

We can fixed this by turning `SentryMiddleware` to be a [factory-based middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-6.0). But this also required some interfaces changes and now all custom event processors will be injected using `PopulateScope` during `OnEvaluation`.

One concern is that this changes might break behaviour of public method `GetAllEventProcessors` since now it can only be used after scope is evaluated. I'm not sure if that could be a concern.

2022-10-08 15:53 UTC, chrisza4 commented on test/Sentry.AspNetCore.Tests/IntegrationsTests.EventProcessor.cs
> +        // exceptionProcessorsResolved[0].DidNotReceive().Process(Arg.Any<Exception>(), Arg.Any<SentryEvent>());
Oops

2022-10-09 16:49 UTC, mattjohnsonpint commented
Thanks for this! Looks promising on first glance.  I'll review in more detail next week.

2022-10-09 23:36 UTC, SimonCropp commented
wouldn't this result in: processors explicitly added to options being ignored?

2022-10-11 00:01 UTC, chrisza4 commented
Few test failed. Let me take a look.


@SimonCropp 
> wouldn't this result in: processors explicitly added to options being ignored?

As I read into [Sentry SDK doc](https://docs.sentry.io/platforms/dotnet/guides/aspnetcore/#adding-event-and-exception-processors), I thought we can only use processors via dependency injection. If there is other way then let me know where and I can take a look.

2022-10-12 21:32 UTC, mattjohnsonpint commented
During initialization, event processors can be added to the options:

```csharp
.UseSentry(options =>
{
    options.AddEventProcessor(new MyEventProcessor());
}
```

They can also be added for a given scope:

```csharp
SentrySdk.ConfigureScope(scope =>
{
    scope.AddEventProcessor(new MyEventProcessor());
});
```

Both of those would need to continue to work.

2022-10-12 21:39 UTC, mattjohnsonpint commented
Looking over the PR, the main issue I see is now *all* processors are registered on the scope.

Instead, let's control this based on how the processor was registered with DI.

- If registered using `AddSingleton`, then it should be applied globally - as if registered directly on the options during initialization.  This is the existing behavior.
- If registered using `AddScoped`, then it should be applied for the current scope - as if registered with `SentrySdk.ConfigureScope`.

2022-10-12 22:17 UTC, mattjohnsonpint commented
Actually, ignore my last comments.  There's no need to separate those paths out, as the effect would be the same as the approach you're currently taking.  In other words, registering the same instance of an event processor on each scope is identical to registering it once on options - since we gather both at the same time when we run them.

2022-10-12 22:20 UTC, mattjohnsonpint commented
I see we are doing this for event processors and exception processors.  Please also do the same for transaction processors added in #1861.  Looks like we missed this back then.  Thanks.

2022-10-12 22:43 UTC, mattjohnsonpint requested changes

2022-10-12 22:43 UTC, mattjohnsonpint commented on src/Sentry.AspNetCore/SentryMiddleware.cs
> +
The null checks are not necessary.

```suggestion
        scope.AddEventProcessors(_eventProcessors.Except(scope.GetAllEventProcessors()));
        scope.AddExceptionProcessors(_eventExceptionProcessors.Except(scope.GetAllExceptionProcessors()));
```

2022-10-12 22:46 UTC, mattjohnsonpint commented
@SimonCropp

> wouldn't this result in: processors explicitly added to options being ignored?

No, because `scope.GetAllEventProcessors()` returns both:

https://github.com/getsentry/sentry-dotnet/blob/77ccdb2dc01b85c1dc53604f9186f715f66b9ff8/src/Sentry/ScopeExtensions.cs#L18-L33

2022-10-12 22:47 UTC, mattjohnsonpint commented
Needs transaction processors added, and a changelog entry, then LGTM.  Thanks!

2022-10-15 23:22 UTC, mattjohnsonpint approved these changes

2022-10-15 23:23 UTC, mattjohnsonpint commented
I added the changelog entry.  We'll do transaction processors in a separate PR.  Thanks for your contribution!

2022-10-15 23:42 UTC, merged