Fix BackgroundWorker exiting when OperationCanceledException is not from shutdown request
getsentry/sentry-dotnet pull request #3284
Opened 2024-04-11 03:05 UTC by phillipcaofph

2024-04-12 12:39 UTC, bitsandfoxes commented
Hey @phillipcaofph, thanks for contributing! I'd love to merge this but we first need to figure out the testing situation as it touches some very internal bits. Thanks for your patience.

2024-04-15 07:54 UTC, jamescrosswell requested changes

2024-04-16 00:42 UTC, phillipcaofph commented on src/Sentry/Internal/BackgroundWorker.cs
> +                    catch (OperationCanceledException) when (shutdownTimeout.IsCancellationRequested)
I'm not sure the best approach to write a test for this scenario. Would be great if you could look at it @jamescrosswell, and for me to learn from 😃

2024-04-16 04:48 UTC, jamescrosswell commented on src/Sentry/Internal/BackgroundWorker.cs
> +                    catch (OperationCanceledException) when (shutdownTimeout.IsCancellationRequested)
No problem and totally understand... there's a lot going on with the tests!

2024-04-24 00:29 UTC, jamescrosswell approved these changes

2024-04-24 00:29 UTC, merged