Default to TraceDiagnosticLogger when running in Visual Studio
getsentry/sentry-dotnet pull request #3373
Opened 2024-05-16 06:02 UTC by jamescrosswell

Resolves https://github.com/getsentry/sentry-dotnet/issues/3341

# TODO

- I need to test this but can't build the Sentry SDK on my Windows box at the moment...

2024-05-22 07:13 UTC, bitsandfoxes commented on integration-test/runtime.Tests.ps1
> +    options.DiagnosticLogger = new ConsoleDiagnosticLogger(SentryLevel.Debug);
```suggestion
    // Some tests rely on the logs being on the console
    options.DiagnosticLogger = new ConsoleDiagnosticLogger(SentryLevel.Debug);
```

2024-05-22 14:26 UTC, bitsandfoxes commented
I did a quick check with our `Blazor.WASM` sample and the logs in the browser seem to rely on the console. Ideally, we'd have some fallback to the console logger on platforms where we know it will go into the void.

2024-05-22 14:27 UTC, bitsandfoxes commented
I'm fine with the behaviour change in general because I assume that this is nothing that affects users in production
It enables debug functionality where it previously did not work.

2024-05-22 22:32 UTC, jamescrosswell commented
> I did a quick check with our `Blazor.WASM` sample and the logs in the browser seem to rely on the console.

Nice catch... tricky though. As we initialise Blazor using plain old `SentrySdk.Init`, I can't think of an easy way to determine, when initialising the SDK, if the app is a Blazor WASM app or not. 

We could create a WASM integration with a`WebAssemblyHostBuilder.UseSentry` extension to initialise the SDK for WASM applications and set `SentryOptions.DiagnosticLogger = new ConsoleDiagnosticLogger(SentryLevel.Debug)` in that case. Given the popularity of Blazor/WASM, it might be worth it to make Sentry as usable as possible in this scenario. We could use that extension method to encapsulate some of the other things involved in correctly configuring the SDK for use with WASM as well.

Alternatively, we could just document/show in the WASM sample that the DiagnosticLogger needs to be set to something non-default (explaining that `Debug.WriteLine` doesn't work in WASM applications).

2024-05-23 18:04 UTC, bitsandfoxes commented
I tried using this all day and I think I changed my mind. I found this to be fairly irritating to have the SDK logs show up somewhere else than the rest of the program's logs.
And when running samples from the command line there were just no logs at all. So I'd have to manually set the `ConsoleDiagnosticLogger` in the options.
TLDR; this felt like a major breaking change.

2024-05-27 10:15 UTC, jamescrosswell commented
> TLDR; this felt like a major breaking change.

We could revisit the initial solution but implement it more simply, like this:

```csharp
public class TraceAndConsoleDiagnosticLogger : DiagnosticLogger
{
    public TraceAndConsoleDiagnosticLogger(SentryLevel minimalLevel) : base(minimalLevel)
    {
    }

    protected override void LogMessage(string message)
    {
        Trace.WriteLine(message);
        Console.WriteLine(message);
    }
}
```

It would create duplication if you had a console tracer configured, but I'd say that's a bit of an edge case (and we could guide people to change the default logger in those cases).

2024-05-29 12:18 UTC, bitsandfoxes commented
I think we agreed on the sync to try to log to both via the MAUI setup to catch those VS users?

2024-06-03 09:50 UTC, bitsandfoxes requested changes

2024-06-04 22:49 UTC, jamescrosswell commented on src/Sentry.Maui/SentryMauiAppBuilderExtensions.cs
> +            services.Configure((Action<SentryMauiOptions>)MauiOptions);
That actually sounded like a really good idea. When I went to implement it however:

a) I spotted this:

https://github.com/getsentry/sentry-dotnet/blob/bd62cf0421cc7a5d7b7804f8461fae00d47d43b8/src/Sentry.Maui/Internal/SentryMauiOptionsSetup.cs#L30-L31

Good, good... so onto the constructor. 
```csharp
        DiagnosticLogger = new ConsoleAndTraceDiagnosticLogger(DiagnosticLevel);
```

The problem with that is that it assumes the `DiagnosticLevel` won't change. If the users sets the `DiagnosticLevel `to anything other than the default, this wouldn't be reflected in the `DiagnosticLogger` that we setup (before they configured that level). 

So I think all of this has to be delayed until where it's being done currently (once we have all the bits of the puzzle to put together).

2024-06-06 14:34 UTC, bitsandfoxes commented on CHANGELOG.md
> +## Fixes
```suggestion
### Fixes
```

2024-06-20 00:15 UTC, jamescrosswell commented on src/Sentry.Maui/SentryMauiAppBuilderExtensions.cs
> +            services.Configure((Action<SentryMauiOptions>)MauiOptions);
No idea what my brain was thinking in the earlier comment. Moving to SentryMauiOptionsSetup seems to work fine.

2024-06-20 09:12 UTC, bitsandfoxes approved these changes
Awesome! Thanks!

2024-06-20 09:12 UTC, merged