Event scrubber
getsentry/sentry-dotnet pull request #3419
Opened 2024-06-13 07:21 UTC by jamescrosswell

Resolves https://github.com/getsentry/sentry-dotnet/issues/3374

2024-06-17 14:13 UTC, bitsandfoxes requested changes
I really like this and I think this is a great feature and quality of life improvement!
It looks like the scrubber is doing quite a bit of work, I think it would make sense to add some benchmarks to it.

2024-06-18 02:35 UTC, jamescrosswell commented on src/Sentry/Internal/EventScrubber.cs
> +        }
I tried that with a benchmark and it increased both the execution time and the allocations:

```diff
| Method                     | Mean     | Error    | StdDev   | Allocated |
|--------------------------- |---------:|---------:|---------:|----------:|
- | ScrubEvent_DefaultDenyList | 39.01 μs | 0.760 μs | 0.961 μs |   4.09 KB |
+ | ScrubEvent_DefaultDenyList | 54.09 μs | 1.165 μs | 3.418 μs |  15.39 KB |
```

2024-06-18 03:04 UTC, jamescrosswell commented
> It looks like the scrubber is doing quite a bit of work, I think it would make sense to add some benchmarks to it.

Done... managed to get execution time down `39.01 μs` to `8.250 μs` and reduced allocations from `4.09 KB` to `2.44 KB`. 

The main improvement came from changing the type of DenyList from `List<string>` to `HashSet<string>`.

2024-06-18 16:42 UTC, bitsandfoxes approved these changes
This is awesome! Thanks for the benchmarks! Wow, quite the improvement!

2024-06-18 23:21 UTC, merged