ref: Remove CultureUiInfo if values are even with CultureInfo
getsentry/sentry-dotnet pull request #671
Opened 2020-12-21 19:23 UTC by lucas-zimerman

Closes #669

2020-12-21 19:43 UTC, lucas-zimerman commented
TaskUnobservedTaskExceptionIntegration.cs | 76.92% <0.00%> (-7.70%)
-- | --
There's no connection between the changes and UnobTaskExpintegration O_o

2020-12-21 22:19 UTC, bruno-garcia reviewed
Thanks for another PR! Left a note thopugh

2020-12-21 22:19 UTC, bruno-garcia commented on src/Sentry/Internal/MainSentryEventProcessor.cs
> +                && currentUiCultureMap.Any(p => cultureInfoMapped.Contains(p) is false))
Just realized there's finally a `TryAdd`:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=net-5.0

So we could avoid the double lookup, but would require adding a polifyll for ns2.0 and net4x.

Also, `is false`, maybe stay with `!` instead?
```suggestion
                && !currentUiCultureMap.Any(p => cultureInfoMapped.Contains(p)))
```

2020-12-22 02:52 UTC, bruno-garcia requested changes

2020-12-22 02:52 UTC, bruno-garcia commented on src/Sentry/Internal/MainSentryEventProcessor.cs
> +                cultureInfoMapped = new Dictionary<string, string>();
Don't allocate here

2020-12-22 02:52 UTC, bruno-garcia commented on src/Sentry/Internal/MainSentryEventProcessor.cs
> +                && currentUiCultureMap.Any(p => !cultureInfoMapped.Contains(p)))
```suggestion
                && cultureInfoMapped is null || currentUiCultureMap.Any(p => !cultureInfoMapped.Contains(p)))
```

2020-12-22 19:21 UTC, bruno-garcia approved these changes
Nice!

CI isn't happy, flaky test?

2020-12-22 19:30 UTC, lucas-zimerman commented
> Nice!
> 
> CI isn't happy, flaky test?

Only on windows, it's failing to restore the Visual Studio packages.

2020-12-22 19:34 UTC, merged