ref: Remove Mono StackTrace Factory.
getsentry/sentry-dotnet pull request #709
Opened 2021-01-01 22:17 UTC by lucas-zimerman

As discussed on Discord, the MonoStackTraceFactory lacks any Assembly information, generating a different grouping compared to the previous stable release (2.1.8).

In addition, since there's no assembly info, the SDK doesn't exclude the known frames that are not part of the user code.
To conclude, the current SentryStackTraceFactory produces richer information when running on mono compared to MonoStackTraceFactory, but it's only lacking the additional info for symbolicate the frames. But since this code wasn't implemented on the server-side, I feel like it's better, for now, to stick to the current StackTraceFactory for mono and in the future, once the symbolization code is ready, enhance the current StackTrace with the needed information.

2021-01-02 21:37 UTC, bruno-garcia commented
> generating a different grouping compared to the previous stable release (2.1.8).

Shouldn't affect grouping though. Did you confirm it does?
It just doesn't show the assembly info UI.

2021-01-02 21:39 UTC, bruno-garcia commented
As we agreed on Discord, please just don't enabled it on `IsMono`?

The code that's there will likely still be needed on IL2CPP or some other Mono-like environment where the `new StackTrace(.., true)` won't work as expected.

2021-01-02 21:40 UTC, bruno-garcia commented on src/Sentry/SentryOptions.cs
> +            SentryStackTraceFactory = new SentryStackTraceFactory(this);
This is the only change we need actually. Just don't add it by default on Mono but keep the code around for now until we're sure we won't need this for Unity

2021-01-02 21:40 UTC, bruno-garcia requested changes
This is the only change we need actually. Just don't add it by default on Mono but keep the code around for now until we're sure we won't need this for Unity

2021-01-04 12:14 UTC, lucas-zimerman commented
Fixxd

2021-01-04 17:22 UTC, bruno-garcia approved these changes
Thanks @lucas-zimerman

2021-01-04 18:05 UTC, merged